name: Storybook Regression Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

env:
  STORYBOOK_PORT: 6006
  LOKI_OUPTPUT_DIR: .loki

jobs:
  test:
    name: Run Storybook Regression Tests
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      # Install dependencies
      - name: Install dependencies
        run: npm install && npm install @rollup/rollup-linux-x64-gnu
      
      # Run Storybook in the background
      - name: Start Storybook
        # run: make storybook-screen-start
        run: |
          npm run storybook -- --host 0.0.0.0 --port 6006 &
          while ! curl --silent --fail http://localhost:6006; do
            echo "Waiting for Storybook to start..."
            sleep 5
          done
          sleep 5
          echo "Storybook started successfully!"
        env:
          STORYBOOK_PORT: ${{ secrets.STORYBOOK_PORT }}
          LOKI_OUPTPUT_DIR: ${{ secrets.LOKI_OUPTPUT_DIR }}
      
      # Wait for Storybook to fully start
      # - name: Wait for Storybook to start
      #   run: |
      #     while ! curl --silent --fail http://localhost:6006; do
      #       echo "Waiting for Storybook to start..."
      #       sleep 5
      #     done
      #     echo "Storybook started successfully!"
      
      # Run the image tests using Loki
      - name: Run image tests
        run: make images-test
        env:
          STORYBOOK_PORT: ${{ secrets.STORYBOOK_PORT }}
          LOKI_OUPTPUT_DIR: ${{ secrets.LOKI_OUPTPUT_DIR }}
      
      # # Stop the Storybook background process
      # - name: Stop Storybook
      #   run: |
      #     screen -S storybook-session -X quit
      #     lsof -t -i:${STORYBOOK_PORT} | xargs kill -9